version: "3"

volumes:
  bundler-data:
    driver: local
  netcdf-data:
    driver: local

services:
  r:
    image: jaydorsey/ghgvcr:latest
    volumes:
      - netcdf-data:/app/data/
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:6311:6311"
    command:
      - /bin/sh
      - -c
      - |
          bin/download-files.sh
          bin/start-server.sh
  app:
    build:
      context: .
    volumes:
      - .:/app
      - bundler-data:/usr/local/bundle
    command:
      - /bin/sh
      - -c
      - |
          bundle check || bundle install
          bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - RAILS_ENV=development
      - CALC_HOST=r
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - r
    stdin_open: true
    tty: true
